### ISSUE TITLE
set cropper height and width

### ISSUE THREAD

**Issue by FahadTariq476-dev** [egorvdovenko/antdv-image-cropper#1]
how to set the cropper height and width??
means it will not resize inside the this height and width.

**Comment by FahadTariq476-dev** [comment]
like setcropperheight  function vue cropper

**Comment by egorvdovenko** [comment]
I'm not sure if I fully understand what you mean...
But you can try using `:full="true"` and `:info-true="true"` attributes on the component, like this:

```
<a-image-cropper
  :auto-crop="true"
  :fixed="true"
  :fixed-number="[2, 1]"
  :full="true"
  :info-true="true"
  output-type="png"
  @crop="onCrop"
>
...
</a-image-cropper>
```

Maybe this will help.

**Comment by FahadTariq476-dev** [comment]
i wanted say that how i fix the size of cropper that is used to crop the selected area of the picture
if i set the cropper height or width cropper not resize after given height and width

**Comment by egorvdovenko** [comment]
You can set default values for width and height:

```
<a-image-cropper
  :auto-crop="true"
  :auto-crop-width="100"
  :auto-crop-height="100"
  output-type="png"
  @crop="onCrop"
>
...
</a-image-cropper>
```

And then allow or disallow changing the crop zone manually using `:fixed-box="true"` attribute or set fixed aspect ratio using `:fixed="true"` attribute.

**Comment by FahadTariq476-dev** [comment]
which attribute use for aspect ratio??

**Comment by egorvdovenko** [comment]
For aspect ratio you can use `:fixed="true"` with `:fixed-number="[2, 1]"`, for example it's 2:1 ratio.

```
<a-image-cropper
  :auto-crop="true"
  :fixed="true"
  :fixed-number="[2, 1]"
  output-type="png"
  @crop="onCrop"
>
...
</a-image-cropper>
```

You can use all props from **vue-cropper** component which are described [here](https://github.com/xyxiao001/vue-cropper/blob/master/english.md).
